baseurl = "http://erikparreira.com/"
title = "ME!!"
languageCode = "en-us"

[params]
  GithubID = "etinlb"
  LinkedInID = "erik-parreira-10349147"
  GoogleplusID = "your_googleplus"
  Name = "Erik"
  HeaderUsername = "username"
  HeaderHostname = "hostname"
  Email = "erik@erikparreira.com"
  About = "I build stuff. Neat Stuff."
  ProfilePicture = "/img/profile.jpg"
  GoogleAnalytics = "UA-85537712-1"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
