baseurl = "http://erikparreira.com/"
title = "Erik Parreira"
languageCode = "en-us"
GoogleAnalytics = "UA-85537712-1"

[Author]
  name = "Erik Parreira"
  email = "erik@erikparreira.com"
  github = "etinlb"
  linkedin = "erik-parreira-10349147"
  googleplus = "+ETParreira" # or xxxxxxxxxxxxxxxxxxxxx
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"

[Params]
  Name = "Erik"
  subtitle = "I build stuff. Sometimes neat stuff."
  navhome = "~baab"

[[menu.main]]
    name = "blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3